version: '3'
services:
  cardarenafe:
    image: 729926669123.dkr.ecr.ap-south-1.amazonaws.com/cardarenafe
    ports:
      - "5173:5173"
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
  cardarenabe:
    image: 729926669123.dkr.ecr.ap-south-1.amazonaws.com/cardarenabe
    ports:
      - "8080:8080"
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    restart: always